# cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/docker
  id: 'android-builder'
  env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  args: [
    'build',
    '-t', 'eu.gcr.io/$PROJECT_ID/android-builder:${SHORT_SHA}',
    '-t', 'eu.gcr.io/$PROJECT_ID/android-builder:latest',

    # These are used by Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', '_ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', '_CLI_TOOLS_VERSION="${_CLI_TOOLS_VERSION"}',
    #'--build-arg', '_GRADLE_VERSION=${_GRADLE_VERSION}',

    # By default these static values are being used, without the NDK (build-trigger configuration not required.
    # Note: When commenting these out, one has to run `./gradlew build` to fetch the components instead.
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-36.1 build-tools;36.1.0  emulator ndk;25.1.8937393',
    '--build-arg', '_ANDROID_SDK_PACKAGES=platform-tools platforms;android-36.1 build-tools;36.1.0  emulator',
    '--build-arg', '_CLI_TOOLS_VERSION=14742923',
    '--build-arg', '_GRADLE_VERSION=9.3.1',

    # enable cloudbuild network
    '--network', 'cloudbuild',
    '.'
  ]

images:
- 'eu.gcr.io/$PROJECT_ID/android-builder:${SHORT_SHA}'
- 'eu.gcr.io/$PROJECT_ID/android-builder:latest'
