# cloudbuild.yaml
steps:
- name: gcr.io/cloud-builders/docker
  id: "cloudbuild-android"
  env:
    - "BUILD=$BUILD_ID"
    - "PROJECT=$PROJECT_ID"
    - "REV=$REVISION_ID"
  args: [
    "build",
    "-t", "europe-west1-docker.pkg.dev/${PROJECT_ID}/ci/android/cloudbuild-android:${SHORT_SHA}",
    "-t", "europe-west1-docker.pkg.dev/${PROJECT_ID}/ci/android/cloudbuild-android:latest",

    # These are used by Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', 'ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', 'GRADLE_WRAPPER_VERSION=${_GRADLE_WRAPPER_VERSION}',

    # By default, static values are being used (build-trigger configuration not required)
    # When commenting these out, one has to run `./gradlew build` to fetch components
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2 ndk;23.1.7779620',
    "--build-arg", "ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2",
    "--build-arg", "GRADLE_WRAPPER_VERSION=7.4.2",

    # enable cloudbuild network
    "--network", "cloudbuild",
    '.'
  ]

images:
  - "europe-west1-docker.pkg.dev/${PROJECT_ID}/ci/android/cloudbuild-android:${SHORT_SHA}"
  - "europe-west1-docker.pkg.dev/${PROJECT_ID}/ci/android/cloudbuild-android:latest"
